flyway.url=jdbc:postgresql://localhost:5432/jufi
flyway.user=postgres
flyway.password=postgres
flyway.locations=filesystem:db-migrations
flyway.defaultSchema=public
flyway.schemas=public
flyway.createSchemas=false