flyway.url=jdbc:postgresql://XXX.h.db.ondigitalocean.com:25060/defaultdb?ssl=true&sslmode=verify-ca&sslrootcert=/Users/texalbuja/.ssh/ca-certificate.crt
flyway.user=doadmin
flyway.password=XXXX
flyway.locations=filesystem:db-migrations
flyway.defaultSchema=public
flyway.schemas=public
flyway.createSchemas=false